---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

```{R, include = FALSE}

library(classdata)
library(tidyverse)

```
Step 1: Inspect the first few lines of the data set:

what variables are there? of what type are the variables? what does each variable mean? what do we expect their data range to be?
```{R}
summary(ames)
```
  Simply running the summary of the data set gives up all the column names and what
